In [1]:
import numpy as np

In [17]:
inputs = [[1,1,0,0,0,0],
        [1,1,0,0,0,1],
        [1,1,0,0,1,0],
        [1,1,0,0,1,1],
        [1,1,0,1,0,0],
        [1,1,0,1,0,1],
        [1,1,0,1,1,0],
        [1,1,0,1,1,1],
        [1,1,1,0,0,0],
        [1,1,1,0,0,1]]

labels = [1,0,1,0,1,0,1,0,1,0]

In [18]:
def step_fun(x):
    if x >= 0:
        return 1
    else:
        return 0

In [19]:
weights = [ 0 , 0 , 0 , 0 , 0 , 1]
print(weights)
print(len(inputs))

[0, 0, 0, 0, 0, 1]
10


In [20]:
for i in range(len(inputs)):
    input_data = np.array(inputs[i])
    label_data = labels[i]
    output = step_fun(np.dot(input_data,weights))
    print(np.dot(input_data,weights))
    error = label_data - output    
    weights += error * input_data
    print(weights)

0
[0 0 0 0 0 1]
1
[-1 -1  0  0  0  0]
-2
[0 0 0 0 1 0]
1
[-1 -1  0  0  0 -1]
-2
[ 0  0  0  1  0 -1]
0
[-1 -1  0  0  0 -2]
-2
[ 0  0  0  1  1 -2]
0
[-1 -1  0  0  0 -3]
-2
[ 0  0  1  0  0 -3]
-2
[ 0  0  1  0  0 -3]


In [35]:
j = 4
input = np.array([int(x) for x in list('{0:06b}'.format(j))])
output = "odd" if step_fun(np.dot(input, weights)) == 0 else "even"
print(j, " is ", output)

4  is  even
